Repository googleapis/python-billingbudgets, pull requests merged in 2021-04, with the labels that each got.

#78 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudbilling, cla: yes, context: full

#79 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#80 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full, samples

#81 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudbilling, cla: yes

#82 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#84 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudbilling, cla: yes
